name: Fetch All Articles

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: fetch-all-articles
  cancel-in-progress: true

jobs:
  build:
    name: "Fetch All Articles"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-cache

      - name: Run Start Script
        run: npm run fetch:all-articles
