name: PR Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  draft:
    name: "Check Draft Status"
    runs-on: ubuntu-latest
    steps:
      - name: "Fail draft PRs"
        if: github.event.pull_request.draft == true
        run: |
          echo "Skipping execution for draft PR"
          exit 1

      - run: echo "PR is not Draft"

  lint:
    name: "Check Lint Status"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
